classdef MpccMethod
    enumeration
        SCHOLTES_EQ
        SCHOLTES_INEQ
        % SCHOLTES_TWO_SIDED
        FISCHER_BURMEISTER_EQ
        FISCHER_BURMEISTER_INEQ
        NATURAL_RESIDUAL_EQ
        NATURAL_RESIDUAL_INEQ
        CHEN_CHEN_KANZOW_EQ
        CHEN_CHEN_KANZOW_INEQ
        STEFFENSEN_ULBRICH_EQ
        STEFFENSEN_ULBRICH_INEQ
        STEFFENSEN_ULBRICH_POLY_EQ
        STEFFENSEN_ULBRICH_POLY_INEQ
        KANZOW_SCHWARTZ_EQ
        KANZOW_SCHWARTZ_INEQ
        LIN_FUKUSHIMA
        KADRANI
    end
end

