classdef NosnocDimensions < handle
    properties
        N_stages
        N_finite_elements
        n_x
        n_f
        n_u
        n_q
        n_z
        n_s
        n_sys
        n_c_sys
        n_f_sys
        n_p_global
        n_p_time_var
        n_contacts
        n_tangents
        n_t
    end
end
